Repository ReyahSolutions/reyah-api-sdk, pull requests merged in 2020-12, with the labels that each got.

#28 Next-generation data models and document models
  .gitignore
  package.json
  src/constructor/dataModel.ts
  src/constructor/documentModel.ts
  src/services/dataModel.ts
  src/types/dataModel.ts
  src/types/documentModel.ts
Labels: C-enhancement, M-mvp3, P-high, S-being-reviewed, T-data-models, T-data-type, T-document-models

#29 Fix gather box camelCase
  package.json
  src/constructor/documentModel.ts
  src/types/documentModel.ts
Labels: C-bug, M-mvp3, P-high, S-waiting-feedback

#30 Added rendering feature
  package.json
  src/constructor/job.ts
  src/services/job.ts
  src/types/job.ts
Labels: C-enhancement, M-mvp3, P-high, S-waiting-feedback

#33 Fixed extraction job output models
  package.json
  src/constructor/job.ts
  src/types/job.ts
Labels: C-bug, M-mvp3, P-high, S-being-reviewed, T-extraction

#34 Fix oauth sql migration
  package.json
  src/constructor/oauth.ts
  src/services/oauth.ts
  src/types/oauth.ts
Labels: C-enhancement, M-mvp3, P-high, S-waiting-feedback

#35 Added location information to extraction jobs output
  package.json
  src/constructor/job.ts
  src/types/job.ts
Labels: C-enhancement, M-mvp3, P-high, S-being-reviewed, T-extraction, T-jobs

#38 Renamed `rows` to `columns`
  package.json
  src/constructor/job.ts
Labels: C-bug, M-mvp3, P-high, S-being-reviewed, T-extraction, T-jobs
