Repository ReyahSolutions/reyah-api-sdk, pull requests merged in 2020-10, with the labels that each got.

#20 DB migration on service.document
  package.json
  src/constructor/documentModel.ts
  src/constructor/job.ts
  src/services/documentModel.ts
  src/types/documentModel.ts
  src/types/job.ts
Labels: C-enhancement, M-mvp3, P-medium, S-waiting-feedback

#21 Remove package lock and fix registry remote
  package-lock.json
  yarn.lock
Labels: C-bug, M-mvp3

#22 Refacto error handling
  .eslintrc.json
  .github/workflows/test.yml
  package.json
  src/constructor/job.ts
  src/core/errors.ts
  src/services/dataModel.ts
  src/services/dataType.ts
  src/services/documentModel.ts
  src/services/job.ts
  src/services/oauth.ts
  src/services/profile.ts
  src/types/documentModel.ts
  src/types/errors/generic.ts
  src/types/errors/index.ts
  src/types/errors/reyaherr.ts
  src/types/job.ts
Labels: C-enhancement, M-mvp3, P-high, S-waiting-feedback, T-extraction

#23 Fix ci/cd authentication
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .npmrc
Labels: C-bug, M-mvp3, P-high, S-waiting-feedback
