Repository ReyahSolutions/reyah-api-sdk, pull requests merged in 2021-02, with the labels that each got.

#43 Fix paginated types / Bump dependencies
  package.json
  src/authentication/authentication.ts
  src/constructor/dataModel.ts
  src/constructor/dataType.ts
  src/constructor/documentModel.ts
  src/constructor/job.ts
  src/core/core.ts
  src/services/profile.ts
  src/types/authentication.ts
  src/types/core.ts
  src/types/dataModel.ts
  src/types/dataType.ts
  src/types/documentModel.ts
  src/types/errors/generic.ts
  src/types/oauth.ts
  src/types/reyah.ts
  yarn.lock
Labels: C-bug, C-dependencies, M-mk4, P-high, S-waiting-feedback

#44 Fix token error detection
  package.json
  src/core/core.ts
Labels: C-bug, M-mk4, P-high, S-waiting-feedback

#45 Feature/invalid status
  package.json
  src/constructor/feed.ts
  src/index.ts
  src/services/feed.ts
  src/types/feed.ts
Labels: C-enhancement, M-mk4, P-medium, S-waiting-feedback, T-acropolis
